---

- name: Download Logstash
  get_url:
    url: "https://github.com/elastic/logstash/archive/refs/tags/v{{ logstash_version }}.tar.gz"
    dest: "/tmp/logstash.tar.gz"

- name: Extract Logstash tarball
  unarchive:
    src: "/tmp/logstash.tar.gz"
    dest: "/usr/local/share"
    remote_src: yes

- name: Deploy Logstash configuration files
  template:
    src: logstash.conf.j2
    dest: "/usr/local/share/logstash-{{ logstash_version }}/config/logstash.conf"
    mode: '0644'

- name: Copy Logstash systemd service file
  template:
    src: logstash.service.j2
    dest: /etc/systemd/system/logstash.service
    mode: '0644'

- name: Reload systemd to pick up Logstash service
  systemd:
    daemon_reload: yes

- name: Ensure Logstash service is running and enabled
  systemd:
    name: logstash
    state: started
    enabled: yes
