---

- name: Add Grafana APT repository key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    update_cache: true

- name: Install Grafana
  ansible.builtin.apt:
    name: "grafana={{ grafana_version }}"
    state: present
    force: true

- name: Deploy Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: '0644'

- name: Ensure Grafana service is running and enabled
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
    daemon_reload: true
