---

- name: Install Grafana
  include_tasks: install.yml

- name: Setup Grafana Datasources
  include_tasks: datasources.yml

- name: Setup Grafana Dashboards
  include_tasks: dashboards.yml
