---
version: 2
updates:
  - package-ecosystem: ansible-galaxy
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
