---

- name: Create Alertmanager user
  ansible.builtin.user:
    name: alertmanager
    system: true
    shell: /bin/false

- name: Create directories for Alertmanager
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'
  loop:
    - /etc/alertmanager
    - /var/lib/alertmanager

- name: Download Alertmanager
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/tmp/alertmanager.tar.gz"
    mode: '0644'

- name: Extract Alertmanager tarball
  ansible.builtin.unarchive:
    src: "/tmp/alertmanager.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64"

- name: Copy Alertmanager binaries to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: alertmanager
    group: alertmanager
    mode: '0755'
    remote_src: true
  loop:
    - alertmanager
    - amtool

- name: Deploy Alertmanager configuration file
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0644'

- name: Deploy Prometheus alert rules
  ansible.builtin.template:
    src: alert_rules.yml.j2
    dest: /etc/prometheus/alert_rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Deploy Alertmanager systemd service file
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'
  notify: Restart Alertmanager
