---

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Ensure outgoing traffic is allowed
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Allow SSH port through UFW (to avoid lockout)
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
  notify: Restart UFW
